dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "3.8"
env:
  global:
  - PIP_USE_MIRRORS=true
install:
  - npm install -g ganache-cli@6.9.1 && ganache-cli -d -p 8545 --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --noVMErrorsOnRPCResponse > /dev/null &
  - pip install -r requirements.txt
script:
  - pytest
