dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "3.8"
env:
  global:
  - PIP_USE_MIRRORS=true
install:
  - npm install -g ganache-cli@6.9.1 && ganache-cli -d -p 8545 --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --noVMErrorsOnRPCResponse > /dev/null &
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls
script:
  - coverage run --source=$SOURCE_FOLDER -m py.test -rxXs
after_success:
  - coveralls
